<a href="https://colab.research.google.com/github/mattpolands/Learning__NumPy/blob/main/MedicalImageNumpyCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#what is numpy
#Python library for creating N-dimensional arrays
#gives us the ability to quickly broadcast functions
#built-in linear algebra, statistical distributions, trigonometric and random number capabilities
#numpy arrays are much more efficient than Python lists
#efficient at broadcasting a function to an entire dataset quickly
import numpy as np


In [ ]:
my_list = [1,2,3]

In [ ]:
#check the data type of my_list
type(my_list)

list

In [ ]:
#can temporarily turn my_list into an array
#using the np.array method and then pass in the object my_list
np.array(my_list)

array([1, 2, 3])

In [ ]:
#make it permanent by naming it
my_array = np.array(my_list)

In [ ]:
type(my_array)

numpy.ndarray

In [ ]:
#transform a nested list into a numpy array
#and in turn building a matrix
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#can determine how many dimensions an array is by the amount of brackets
#two brackets above so we have an x and y dimension
#name above
my_matrix = np.array(mylist)

In [ ]:
#can now run a whole bunch of methods off of this object
#example
my_matrix.shape

(3, 3)

In [ ]:
#just beginner tip you have to ensure that the object is defined before you are able to tab in a method
#np.arange(a start, a stop, a stepwise)
#our start number and then up to the number we have chosen as our stop number
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#default stepwise is 1 as seen above, but can be chosen
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
#computers use 1s and 0s
#numpy allows you to create arrays that reflect this
#below creates five floating zeros
#numbers that be fractionalized 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#can also create multiple dimensions by passing a tuple as the object into zeros method
#tuple represented by the additional parentheses
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#3D
np.zeros((4,10,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
#numpy is used because it allows you to do things that simply cannot be done in Python
#example
np.ones((4,3)) + 6

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [ ]:
#the versatility of numpy allows you to perform an operation on every element of an array
#Python alone cannot do this

In [ ]:
#numpy also allows you create linearly spaced arrays
#np.linspace(a start, a stop, how many items we want between the start and the stop)
#example I want 50 items (as floating numbers) between the integers 1 and 11 all EVENELY SPACED
np.linspace(1,11,50)

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

In [ ]:
#for record with numpy you can also create identity matrices
#a matrix the has ones down the diagonal and the rest are zeros
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#numpy has a built in random number generator
#return a random number between 0 and 1
#random library allows you to pick a slew of methods
#rand picks a random sample from a uniform distribution between 0 and 1
np.random.rand(1)

array([0.1033135])

In [ ]:
np.random.rand(6)

array([0.84391231, 0.38386129, 0.85033525, 0.98145179, 0.17530729,
       0.77332546])

In [ ]:
np.random.rand(5,3)

array([[3.29968269e-01, 9.03604451e-01, 8.17490476e-01],
       [5.88048630e-01, 5.63731350e-01, 7.04886477e-02],
       [4.61413422e-03, 4.37426836e-01, 2.78997822e-01],
       [3.94421549e-01, 3.31738315e-01, 8.43584046e-01],
       [1.59012747e-01, 8.29545445e-04, 2.65045258e-01]])

In [ ]:
#randn - the little n stands for normal standard distribution
#randn pulls a random sample from a normal standard distribution
#what normal standard distribution means is that the mean lays at 0 with a standard deviation of 1
#this result can give us negative floating numbers
np.random.randn(3)


array([-0.17053469,  0.80772574, -1.62681474])

In [ ]:
np.random.randn(3,4)

array([[-0.57662228, -0.5051625 , -2.3329931 , -0.8155388 ],
       [ 0.12883728,  0.34582698,  0.25184155,  2.65584833],
       [ 0.38571487,  0.30017681, -0.66523181,  0.00631499]])

In [ ]:
#can also create your own mean and sigma (ie std) off a normal distribution using the method normal
#np.random.normal(loc = mean, scale = sigma, size = desired # of elements)
np.random.normal(24,2.7,75)

array([23.18084477, 22.99171584, 21.35112399, 25.96308526, 19.78133794,
       23.76540387, 26.05843624, 23.65703386, 23.50869496, 23.71359157,
       25.0331576 , 22.100159  , 22.07083864, 24.68239492, 19.21246743,
       26.47046749, 21.84446808, 19.99204698, 20.04805115, 26.1868253 ,
       25.69769443, 21.77149   , 24.96982521, 25.89871474, 24.86444014,
       21.12449011, 22.22314887, 18.30811996, 26.72275915, 29.56209267,
       22.90043038, 24.53597739, 29.58040146, 20.5698958 , 23.73947777,
       21.98190953, 23.16766803, 23.0132509 , 23.7472943 , 23.48794405,
       26.37859219, 19.42519484, 22.34927055, 21.30567135, 20.67707609,
       25.91053726, 29.19867195, 25.55700484, 21.60792003, 21.46523363,
       25.08828335, 23.73737333, 22.08824791, 20.71063375, 22.10074901,
       24.18704584, 22.67535099, 23.92415445, 27.22783933, 25.07069383,
       25.80099156, 20.20724642, 24.95223781, 24.68302167, 25.25066599,
       21.84405518, 24.18143631, 19.11234489, 23.49629598, 22.33

In [ ]:
#pull random integers
#np.random.randint(low = a starting point, high = a stopping point, size = how many random numbers)
np.random.randint(4,73,12)

array([35, 55, 11, 57, 15, 28, 18, 44, 12,  9, 24, 47])

In [ ]:
#can ensure that the same set of random numbers are chosen
#may be useful if trying to replicate results
#do this by creating a "seed"
#seed number is arbitrary
np.random.seed(42)
np.random.randint(4,73,12)

array([55, 18, 64, 24, 27,  6, 25, 56,  5, 33, 41,  5])

In [ ]:
np.random.randint(4,73,12)

array([67, 63, 24, 36, 61, 25, 52, 62, 45, 63, 18, 65])

In [ ]:
np.random.seed(42)
np.random.randint(4,73,12)

array([55, 18, 64, 24, 27,  6, 25, 56,  5, 33, 41,  5])

In [ ]:
array = np.arange(25)

In [ ]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
randarray = np.random.randint(5,68,12)

In [ ]:
randarray

array([55, 16, 50, 42, 14, 51, 66,  6, 53, 59, 28,  6])

In [ ]:
array.shape

(25,)

In [ ]:
#can change the shape
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#key factor can only reshape into an array that fits the original amount of elements
#ie can not reshape the 1D array of 25 into the 2D array of 5,3 (that only fits 15 elements)

In [ ]:
randarray.max

<function ndarray.max>

In [ ]:
#have to use the parentheses at the end to "call" the object
randarray.max()

66

In [ ]:
randarray.min()

6

In [ ]:
#want to pull the max or min element location in the index
randarray.argmax()

6

In [ ]:
randarray.argmin()

7

In [ ]:
randarray[6]

66

In [ ]:
randarray[7]

6

In [ ]:
array2 = np.arange(0,11)

In [ ]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#indexing
array2[3]

3

In [ ]:
array2[2:8]

array([2, 3, 4, 5, 6, 7])

In [ ]:
#once again the major advantage of numpy arrays is the ability to broadcast
#ie arithmetic simultaneously to each element of an array
#several examples below
array2 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
array2 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
array2**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
#more complex use of broadcasting
slice_of_pie = array2[1:6]

In [ ]:
slice_of_pie[:] = 99

In [ ]:
slice_of_pie

array([99, 99, 99, 99, 99])

In [ ]:
#because a new variable has been defined/named ("slice_of_pie") the changes are permanent
array2 

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#example how to avoid this is needed/wanted
array3 = array2.copy()

In [ ]:
array3[:] = np.arange(0,11)

In [ ]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
array2

array([ 0, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
array2D = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
array2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
#indexing on 2D arrays
#grab 30
array2D[1][2]

30

In [ ]:
#can also slice index
#grab 45
array2D[2,2]

45

In [ ]:
#pull 10 and 15
array2D[:1,1:]

array([[10, 15]])

In [ ]:
#conditional selection
#important for use in pandas
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
array3 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
#answers in terms of boolean
#name it
boolean_array3 = array3>4

In [ ]:
boolean_array3

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
array3[boolean_array3]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#above only returns values that are 'True'
#easier, faster, more efficient way to do this below
array3[array3>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
#more complex broadcasting
(array3**2)/2

array([ 0. ,  0.5,  2. ,  4.5,  8. , 12.5, 18. , 24.5, 32. , 40.5, 50. ])

In [ ]:
array3 + array3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#examples of arithmetic methods in numpy
np.sqrt(array3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
#"inf" equates to infinity
np.log(array3)

<ipython-input-57-d1306bb322ee>:2: RuntimeWarning: divide by zero encountered in log
  np.log(array3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
np.sin(array3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.sum(array3)

55

In [ ]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#in a 2d or above array you can choose the axis with your operations
#axis default is none, axis 1 = rows, axis 0 = columns
arr2d.sum(axis=1)

array([10, 26, 42])

In [ ]:
arr2d.sum(axis=0)

array([15, 18, 21, 24])

In [ ]:
#exercises 
#create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
array_of_5s = np.ones(10)

In [ ]:
array_of_5s[:] = 5

In [ ]:
array_of_5s

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#or
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrix3x3 = np.random.rand(3,3)

In [ ]:
matrix3x3

array([[0.99313896, 0.43331508, 0.65651682],
       [0.75838745, 0.70253072, 0.08950696],
       [0.61362466, 0.56272314, 0.30228102]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.rand(1)

array([0.16858538])

In [ ]:
np.random.randn(25)

array([-1.202283  , -0.97167794, -0.1589154 ,  1.25716068, -1.18940754,
        1.26928493,  0.80011999, -0.13155896, -2.17278207, -0.65868839,
        1.30403862, -0.52771346,  0.44025321,  1.28829675,  1.20790081,
        0.67145487, -0.32708273, -0.09509888, -0.67877269, -1.06643403,
        0.48501416,  1.12390561,  1.69924488,  1.25771396, -1.224012  ])

In [ ]:
arr = np.arange(100)/100

In [ ]:
arr.reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [ ]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3][4]

20

In [ ]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
#or
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat.sum()

325

In [ ]:
mat.std()

7.211102550927978

In [ ]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])